### PR TITLE
Add arabic cases page

### PR DESCRIPTION
**Pull request by kamicut**
- [x] Cases
- [x] Single case page
- [x] About
- [x] Report page

### CODE REVIEW

**Comment by kamicut** [comment]
@GrantBaker22 You can click on "View deployment" to preview the arabic pages. 
untitled

**Comment by kamicut** [comment]
Before I merge this in @GrantBaker22, could you all take a look at the arabic text?

**Comment by GrantBaker22** [comment]
https://docs.google.com/document/d/1RWxzWZhNaiAfgzaSykFMIvoFv1foUF4CxktNmMbF0Bg/edit?ts=5c755021

**Comment by GrantBaker22** [comment]
Hi Marc, the about section in Arabic has been updated here as well. https://docs.google.com/document/d/1vYb6YVo_pbi8b6eV9PXzcd6oa7FJpaAbbxCt1jdf3hM/edit

**Pull request merged**
